query RunInput {
  shop {
    groupRules: metafield(namespace: "gd_wholesale_pro", key: "group_rules") {
      value
    }
  }
  cart {
    attribute(key: "gd_b2b_checkout_retail") {
      value
    }
    buyerIdentity {
      customer {
        hasAnyTag(tags: ["B2B_approved"])
        groupTags: hasTags(tags: [
          "B2B_approved",
          "B2B_wholesale",
          "B2B_distributor",
          "B2B_vip",
          "B2B_gold",
          "B2B_silver",
          "B2B_bronze",
          "B2B_dealer",
          "B2B_partner",
          "B2B_trade",
          "Wholesale",
          "Distributor",
          "VIP",
          "Gold",
          "Silver",
          "Bronze",
          "Dealer",
          "Partner",
          "Trade"
        ]) {
          tag
          hasTag
        }
      }
    }
    cost {
      subtotalAmount {
        amount
      }
    }
    lines {
      id
      quantity
      cost {
        amountPerQuantity {
          amount
          currencyCode
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          metafield(namespace: "$app", key: "gd_b2b_price") {
            value
          }
          minQtyMetafield: metafield(namespace: "$app", key: "gd_b2b_min_qty") {
            value
          }
        }
      }
    }
  }
}
